services:
  database:
    image: postgres:15-alpine
    container_name: calibraflow-db
    restart: always
    environment:
      - POSTGRES_DB=calibraflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data-NOVO:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5