spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

datafixer:
  input:
    filename: instrumentos_completo.csv
    directory: ./backend/src/main/resources
  output:
    filename: instrumentos_limpos.csv
    directory: ./backend/src/main/resources
  processing:
    skip-lines: 5

api:
  security:
    token:
      secret: ${JWT_SECRET:calibraflow-secret-default}
      expiration: 7200000 # 2 horas
    refresh-token:
      expiration: 86400000 # 24 horas