spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/calibraflow}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  config:
    import:
      - optional:file:.env
      - optional:file:./backend/.env
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: calibraflow@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

datafixer:
  input:
    filename: instrumentos_completo.csv
    directory: ./data/input
  output:
    filename: instrumentos_limpos.csv
    directory: ./data/input
  processing:
    skip-lines: 5

api:
  security:
    token:
      secret: ${JWT_SECRET:calibraflow-secret-default}
      expiration: 7200000
    refresh-token:
      expiration: 86400000